export const PlasmaBattleAlphaAbi: any = [
  {
    type: "constructor",
    inputs: [{ name: "_signer", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "battleId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "battleRecord",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "player", type: "address", internalType: "address" },
      { name: "result", type: "uint8", internalType: "enum Result" },
      { name: "startTimestamp", type: "uint256", internalType: "uint256" },
      { name: "endTimestamp", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "endBattle",
    inputs: [
      { name: "_battleId", type: "uint256", internalType: "uint256" },
      { name: "_result", type: "uint8", internalType: "enum Result" },
      { name: "_signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getEnemyUnits",
    inputs: [{ name: "_stage", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256[5]", internalType: "uint256[5]" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getPlayerUnits",
    inputs: [{ name: "_player", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[5]", internalType: "uint256[5]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubUnits",
    inputs: [{ name: "_player", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[5]", internalType: "uint256[5]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "newUnits",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerStage",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSigner",
    inputs: [{ name: "_signer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "signer",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "startBattle",
    inputs: [
      { name: "_playerUnits", type: "uint256[5]", internalType: "uint256[5]" },
      { name: "_subUnits", type: "uint256[5]", internalType: "uint256[5]" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validateUnits",
    inputs: [
      { name: "_stage", type: "uint256", internalType: "uint256" },
      { name: "_playerUnits", type: "uint256[5]", internalType: "uint256[5]" },
      { name: "_subUnits", type: "uint256[5]", internalType: "uint256[5]" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    name: "BattleIdIncremented",
    inputs: [
      {
        name: "battleId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BattleRecorded",
    inputs: [
      {
        name: "battleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "result",
        type: "uint8",
        indexed: true,
        internalType: "enum Result",
      },
      {
        name: "startTimestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTimestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BattleAlreadyEnd", inputs: [] },
  { type: "error", name: "BattleNotStartedYet", inputs: [] },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [{ name: "length", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureS",
    inputs: [{ name: "s", type: "bytes32", internalType: "bytes32" }],
  },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidUnitId", inputs: [] },
  { type: "error", name: "MustResultEnd", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
];
